### ISSUE TITLE
$${raw} with a transform not giving full tag.

### ISSUE THREAD

**Issue by MorpheusUK** [getwud/wud#200]
Hello,
I recently added snapdrop into my list of images which uses tags in the following format: 68347061-ls74

Looking at the github page the last number after the "ls" increments with releases(https://github.com/linuxserver/docker-snapdrop/releases) so with that in mind I implemented a transform to extract the numerical version as follows:
```
      - 'wud.tag.include=^.*-ls\d+$$'
      - 'wud.tag.transform=^.*-ls(\d+)$$ => $$1'
      - 'wud.link.template=https://github.com/linuxserver/docker-snapdrop/releases/tag/$${raw}' 
```
On the face of it this seems to work and in the above example extracts the 74 however when I attempt to use the $${raw} to get the full pre-transform tag to add to the link template it instead gives me the result of the transform (74) instead of the original tag (68347061-ls74).

Is this correct? If so is there anyway to get the pre-transformed tag?

Thanks.

**Comment by mlofjard** [comment]
I've got the same problem. I've transformed a long tag from linuxserver to get a valid semver (for version checking) but now I can't link to the github page because it does not have a tag in the transformed format.

I suggest an additional ${rawPre} or ${preRaw} (or something else) that contains the tag PRE-transform. I might do a PR for this after christmas.

**Comment by fmartinou** [comment]
New variables has been added to keep access to the original tag value:
- `${original}` the original unparsed tag
- `${transformed}` the original unparsed tag transformed with the optional `wud.tag.transform` label option
- `${major}` the major version (if tag value is semver)
- `${minor}` the minor version (if tag value is semver)
- `${patch}` the patch version (if tag value is semver)
- `${prerelease}` the prerelease version (if tag value is semver)
