### ISSUE TITLE
Feature request: Button for Trigger testing

### ISSUE THREAD

**Issue by ptC7H12** [getwud/wud#319]
Hello,

when you set up a trigger it would be great to set up "Test" Button to se wether the Trigger works.

**Comment by r3mi** [comment]
+1
would be useful to be able to test triggers configuration

**Comment by kuya1284** [comment]
The only way that I know of to test a trigger is to use **Watch Now** button on the **Containers** tab. The issue that I have with this is that it requires `WUD_TRIGGER_{{trigger_type}}}_{trigger_name}_ONCE` to be set to `false` and will process all containers. If we wanted a way to simply test a trigger (i.e. SMTP) to make sure a connection is being established along with testing `WUD_TRIGGER_{{trigger_type}}}_{trigger_name}_SIMPLETITLE` or `WUD_TRIGGER_{{trigger_type}}}_{trigger_name}_SIMPLEBODY`, there's no simple way to do that. I could see rate limits getting hit pretty quick without the ability to send a test notification with dummy data.

**Comment by kingp0dd** [comment]
+1

**Comment by fmartinou** [comment]
Hi, it has been implemented: see https://github.com/getwud/wud/issues/500
(available from `7.2.0`)

**Comment by kuya1284** [comment]
Thank you for this helpful improvement, @fmartinou.
