### ISSUE TITLE
Feature request: Trigger integration with Gotify

### ISSUE THREAD

**Issue by sanello84** [getwud/wud#321]
Hello,

Integration with a free option for self-hosted push notification service like Gotify would be greatly appreciated.

https://github.com/gotify

Thank you!

**Comment by whvneo** [comment]
This should be easy enough as a copy from HTTP trigger which renders SIMPLETITLE and SIMPLEBODY with some extra stuff to show Makrdown message.

**Comment by fmartinou** [comment]
Hi, btw, Gotify trigger is available from version `7.1.0` 😃 .
