### ISSUE TITLE
distinct webhook by container

### ISSUE THREAD

**Issue by ar3thien** [getwud/wud#412]
Is it possible to have a distinct webhook by container? my use case is the following: whenever "whats-up-docker" detects an update, it sends a webhook to trigger an upgrade pipeline. the pipeline is distinct per container.

**Comment by fmartinou** [comment]
Hi,

A new feature has been released yesterday: https://github.com/getwud/wud/issues/502

It might be a solution to your issue.

You can:
1. Create all the trigger webhooks you need
2. Associate each container to the right trigger
