### ISSUE TITLE
[Question/Request] Is there(/Could there be) a way to manually trigger an update?

### ISSUE THREAD

**Issue by Daemonias** [getwud/wud#428]
I have setup WUD in a way that lets me know when there are updates available.
And it does a commendable Job of it. But now that I know there are updates how do I continue?

What I'm not finding/missing is a button to update the containers that have an update ready and that I want to update.

The way I understand it at the moment I can either have WUD autoupdate all/certain containers or just tell me there are updates.. nothing in between.

**Comment by armond-avanes** [comment]
I believe there is already an existing ticket for this: https://github.com/fmartinou/whats-up-docker/issues/210
You might want to post on that discussion thread.

**Comment by fmartinou** [comment]
I close this issue in favor of #210 .
