### ISSUE TITLE
Trouble with configuring Apprise API options

### ISSUE THREAD

**Issue by Nelluk** [getwud/wud#459]
I am having trouble getting my configuration right for sending notifications to my Apprise API instance. I have gotten my apprise notifications working with other apps (audiobookshelf, radarr, etc), but this one I have not been able to set up correctly.

Here are a couple of variations I've tried in the docker-compose.yml file:
```
      - WUD_TRIGGER_APPRISE_APPRISE1_URL=http://192.168.1.201:8000/
      - WUD_TRIGGER_APPRISE_APPRISE1_CONFIG=884redacted70db  
      # - WUD_TRIGGER_APPRISE_APPRISE1_TAG=home
```

```
      - WUD_TRIGGER_APPRISE_APPRISE1_URL=http://192.168.1.201:8000/
      - WUD_TRIGGER_APPRISE_APPRISE1_URLS=apprise://192.168.1.201:8000/884redacted70db/?tags=all
      # - WUD_TRIGGER_APPRISE_APPRISE1_TAG=home
```

I've tried it with and without the TAG config active.
Sometimes I'll get a warning in the WUD logs like this:

```
10:27:54.589  WARN whats-up-docker/trigger.apprise.apprise1: Error (404 - "\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Not Found</title>\n</head>\n<body>\n  <h1>Not Found</h1><p>The requested resource was not found on this server.</p>\n</body>\n</html>\n") (container=local_birdcage-redis-1)
```

In other apps where I've been successful, I've just had to give the base URL and the `884redacted70db` as a persistent storage key.

**Comment by Nelluk** [comment]
> Hi, did you solve? I am also struggling with apprise, same situation as yours. Am using persistent YAML.

Yes. I found the documentation confusing for my particular use case, but was able to stumble into a working config.

```
- WUD_TRIGGER_SMTP_APPRISE1_SIMPLETITLE=WUD Update - container $${name} can be updated
- WUD_TRIGGER_APPRISE_APPRISE1_URL=http://192.168.1.201:8000
- WUD_TRIGGER_APPRISE_APPRISE1_URLS=apprise://192.168.1.201:8000/*myappriseconfigkeyhere*/?tags=all
- WUD_TRIGGER_APPRISE_APPRISE1_ONCE=false
- WUD_TRIGGER_APPRISE_APPRISE1_MODE=batch
```

**Comment by fmartinou** [comment]
Hi @Nelluk ,

I'm not an expert of Apprise so if you think that the documentation can be improved to help onboarding users ; please, feel free to contribute 👍.
