### ISSUE TITLE
Containers are not sorted by name

### ISSUE THREAD

**Issue by ngosang** [getwud/wud#467]
Version 7.0.0

Alertmanager should be the first.
![image](https://github.com/user-attachments/assets/e43aedc4-336d-48df-b289-908de4215271)

They are in different Registry:
![image](https://github.com/user-attachments/assets/e527074b-3859-4b19-b535-d63225abe2f0)

**Comment by fmartinou** [comment]
I see... it's a regression caused by that one https://github.com/getwud/wud/issues/444

Prior, registry names was also part of the title so things where properly sorted...

I'll fix the sort function to match the UI display.
