### ISSUE TITLE
Feature request: Show the complete URL of the Docker image

### ISSUE THREAD

**Issue by ngosang** [getwud/wud#468]
For the me most useful info of the Docker image is the complete URL like:
* gcr.io/cadvisor/cadvisor:v0.49.1
* prom/node-exporter:v1.8.2

I can find the repository, the image and the version in different parts.
I can't find the URL (gcr.io)
I also think that the most important fields should be on the first tab to make it easier. For me they are these:
* Image name (or complete URL)
* Current version
* New version
* Link to the changes
* Link to the Registry page (new feature)

Fields like ID and  Link template are too technical to be in the first tab

![image](https://github.com/user-attachments/assets/ed2397d9-da3d-42c5-99bd-8c0a950a3dbe)
![image](https://github.com/user-attachments/assets/a55c4c44-2b82-4e1c-91cf-0f2ced0841fe)
![image](https://github.com/user-attachments/assets/36dee091-31d5-49e5-aa45-e6a42d93ba11)

**Comment by fmartinou** [comment]
Thank you for your feedback; I'll see how I can improve the UX 👌

**Comment by fmartinou** [comment]
The "update" tab is now at the first position; it should resolve all your points 🤞 
![image](https://github.com/user-attachments/assets/923c3de8-caea-4c2f-97ee-678f67d5e1a5)

**Comment by ngosang** [comment]
Thank you very much!
