### ISSUE TITLE
Feature Request: Improve new version location / user experience

### ISSUE THREAD

**Issue by ngosang** [getwud/wud#469]
This is my flow when I'm reviewing/updating my Docker containers.

1. I use the filters on top. They are fine.
![image](https://github.com/user-attachments/assets/0b8b0a2a-d74e-40a3-bf2a-216e7799de2a)

2. I read the container name (**I don't care about the watcher because I only have 1**) and compare the current and new version. In my screen **those numbers are too far away to make it easy to compare.**

![image](https://github.com/user-attachments/assets/29190f87-7687-480c-be70-0e819959bd75)

3. I click on the Link to read the release notes. That is the only info I care about and it's at the bottom.
![image](https://github.com/user-attachments/assets/93948766-340e-488e-ad56-af83d01708d2)
In fact, the info in the Update tab is enough, but it's the last tab.
![image](https://github.com/user-attachments/assets/bc18ef25-cf5e-4bea-a74b-8a3cc08dc3ea)

4. I copy the new version for the UI. That's fine.

I can't give you advice about how to change the UI / UX but I hope you can improve it someway. Thank you for this software. It's very useful for me.

**Comment by fmartinou** [comment]
Thank you for your feedback 👍.

It's always valuable; I'll see how I can improve the UX 👌

**Comment by fmartinou** [comment]
I revamped the UI to take your feedback in consideration:

![image](https://github.com/user-attachments/assets/310d550c-9625-45c1-b347-fa2c50131186)

**Comment by ngosang** [comment]
Thank you very much! I will give you feedback when you publish the release.
