### ISSUE TITLE
Missing Packages on GHCR

### ISSUE THREAD

**Issue by Bottleface** [getwud/wud#478]
I am trying to switch the image to use the new `getwud` organization.  I would prefer to use ghcr given docker hub's rate limiting.  I updated my docker compose to use `ghcr.io/getwud/wud` as[ stated in the quickstart](https://getwud.github.io/wud/#/quickstart/:~:text=Please%20notice%20that%20wud%20is%20available%20on%20multiple%20container%20registries%0A%2D%20Docker%20Hub%3A%20getwud/wud%0A%2D%20Github%20Container%20Registry%3A%20ghcr.io/getwud/wud).
![image](https://github.com/user-attachments/assets/1fe7e14d-021a-400a-8a22-5a3925f9c9d1)

As soon as I did this docker failed to pull the image.

> `Error response from daemon: Head "https://ghcr.io/v2/getwud/wud/manifests/latest": denied`

And sure enough, pulling that manifest results in the following response.

```
{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "authentication required"
        }
    ]
}
```

I also checked out the packages on this repo and couldn't find any.

https://github.com/orgs/getwud/packages?repo_name=wud

Is there something simple that I'm missing or is there an issue with the package that is supposedly published to the ghcr.io registry?

I can use docker hub, would just rather not if there is an alternative.

**Comment by fmartinou** [comment]
Hi,

You're right; the packages are missing.
There must be a glitch on the CI that prevented packages to be pushed to ghcr 🤔 .
I'll take a look.

**Comment by Bottleface** [comment]
That would make sense.  I can use the DockerHub image for now.  I'll check back periodically for when the images are published to GitHub.  Thanks for this project, it's a game changer for those who use docker a lot.

**Comment by fmartinou** [comment]
GHCR packages are back (from `7.1.1`)

=> https://github.com/orgs/getwud/packages/container/package/wud
