### ISSUE TITLE
Feature Request or Question Lock WUD to tags

### ISSUE THREAD

**Issue by soloam** [getwud/wud#487]
Hello is it possible to lock WUD to tags! Some containers I have them in a specific release for a reason! And I keep getting notifications of new versions! Also some newer images are for beta versions or for test versions, and I would only like to get notifications for tags that I specify on the container! I know that if I set a specific version on a container I would never see a update, the perfect world would be to specify that based on container, but if that's not possible I would have it general and manage that myself!

Thank you

**Comment by fmartinou** [comment]
Hi,

You can put `wud.tag.include` and `wud.tag.exclude` labels to your container to specify extra regex to define acceptable tag formats.

Example:
```yaml
  mariadb:
    image: mariadb:10.4.5
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
```

You'll find the [complete doc here](https://getwud.github.io/wud/#/configuration/watchers/) and [many examples there](https://getwud.github.io/wud/#/configuration/?id=complete-example)

Would that solve your issue?

**Comment by soloam** [comment]
This is great! So also can I make it only allow a specific tag, like main or latest? Without regex? Or to a specific container lock to version 1.1 for example!?

Thank you

**Comment by fmartinou** [comment]
Both are possible.

If you specify a regex capturing semver tags (eg 1.2.3), you'll be notified when a new matching tag shows up.

If you specify a regex capturing non semver tags (eg main or latest), you'll be notified when the hash associated to the tag has changed.

**Comment by soloam** [comment]
Tks and great work

**Comment by soloam** [comment]
Just a heads up, you have a little typo on the docs!

![Screenshot_20241115-011201.png](https://github.com/user-attachments/assets/55dd106a-c341-4294-bfaf-3dda60ed3c28)

It says You can filter (by inclusion or inclusion), probably it should be "You can filter (by inclusion or exclusion)"

Thsnks for your help

**Comment by soloam** [comment]
This is closed! Thank you for the help
