### ISSUE TITLE
Add check for image architecture

### ISSUE THREAD

**Issue by mgite** [getwud/wud#488]
I have configured WUD to notify me whenever there are updates. I have regex for tags, but there is no option to match architecture. about 15 minutes ago it notified me that there is postgresql 17.1 release update. I tried updating it manually like i always do and it gave me an error

`no matching manifest for linux/amd64 in the manifest list entries
`

Because it's probably built for another arch but not amd64 version yet, but WUD saw that 17.1 is already available.

It would be cool if there was an option to specify architecture to monitor.

**Comment by fmartinou** [comment]
That's strange because WUD looks for candidates that matches the exact same architecture as the architecture of the locally running container 🤔

**Comment by fmartinou** [comment]
I'm wondering if there is not a glitch in the latest postgres images push.
From the UI of the Docker hub, under the tags pushed 2 hours ago, there is no details regarding the size or the layers 🤔.
I'm maybe tired and don't see clear but I find it suspicious.

**Comment by fmartinou** [comment]
Postgres images seem to be back to normal:

![image](https://github.com/user-attachments/assets/2789e12e-0c6f-4cb0-a4eb-2ad028f7610b)

I close this issue because, to me, it was a bug caused by postgres when they (half) pushed some tags.

**Comment by jasoncodes** [comment]
I’ve run into this multiple times now with Docker images. Right now [`docker:28.3.0-dind-rootless`](https://hub.docker.com/_/docker/tags?name=28.3.0-dind-rootless) only has an `linux/amd64` image:

```
$ docker pull docker:28.3.0-dind-rootless
28.3.0-dind-rootless: Pulling from library/docker
no matching manifest for linux/arm64/v8 in the manifest list entries
```

WUD is reporting `28.3.0-dind-rootless` as available but it’s not yet. I’ve double checked the currently running `28.2.2-dind-rootless` image is `linux/arm64`.

**Comment by m-a-v** [comment]
I've just had an issue that on my linux/amd64 system and update was triggered, although there is no manifest for the architecture. This resulted in Nextcloud not running anymore.

```
docker pull nextcloud:31.0.9-fpm-alpine
31.0.9-fpm-alpine: Pulling from library/nextcloud
no matching manifest for linux/amd64 in the manifest list entries
```

Could we add another layer of security to assure that the docker pull will work?

@fmartinou Reopen?

**Comment by jasoncodes** [comment]
I’ve just run into this again with `python:3.14.7-alpine` released today. Ended up with an `armv7l` image instead of the expected `aarch64` image like I was running with `python:3.14.6-alpine`. New container crashed hard and I ended up with gigabytes of `qemu_python3_20260805-…` core dumps. 😅

I’m running WUD 8.3.1.
