### ISSUE TITLE
Feature Request - Add stack to the UI

### ISSUE THREAD

**Issue by soloam** [getwud/wud#489]
Hello, is it possible to add to the ui, when a container is created with docker compose, the name of the stack prior to the name of the container? this would help to identify the container quickly when multiple containers have similar names but are inside a stack!

Thank you
Best Regards

**Comment by fmartinou** [comment]
Hi,

Stacks only exist when using _Docker Swarm_ if I'm not wrong.

As for now, _Docker Swarm_ is not explicitly supported but maybe in the future...
=> https://github.com/getwud/wud/discussions/472
