### ISSUE TITLE
Is it possible to get notifications only when new versions are available while using the latest tag?

### ISSUE THREAD

**Issue by rafapirotto** [getwud/wud#497]
Hey! First of all thanks for this amazing piece of software!

Secondly, I want to explain my use case (if it makes sense at all).

I'm interested in knowing whenever a new version (be it a major, minor or patch) is available. I wanna know if that is possible while using the `latest` tag together with the watch digest flag turned off. Like, can wud obtain the version from the `latest` tag? Does it make sense to do so?

Like when will I get a notification if I set a container with the `latest` tag but turn off the watch digest flag?

The motivation behind this is avoid setting a fixed semver tag to all of my images

Thanks!

**Comment by fmartinou** [comment]
Hi,

Thank you for your support 👍 .

> The motivation behind this is avoid setting a fixed semver tag to all of my images

Unfortunately the primary goal of `wud` is to stop using `latest` tags 😄... in favour of `semver` tags to ensure container immutability.

If I understand what you look for, you'd expect `wud` to:
1. Get the digest of the running container with tag `latest` (let's call it _digest_current_)
2. Find on the registry if this _digest_current_ is also associated to another `semver` tag  (let's call it _semver_tag_current_)
3. Get on the registry the digest associated to the `latest` tag (let's call it _digest_registry_)
4. Find on the registry if this _digest_registry_ is also associated to another `semver` tag  (let's call it _semver_tag_registry_)
5. Compare the 2 semver tags
6. Trigger a notification indicating that _semver_tag_registry_ is greater than _semver_tag_current_ (or that _digest_registry_ is newer than _digest_current_)

It seems very complicated to implement (I don't even know if it's possible using the Docker Registry API by the way 🤔 ).

**Comment by rafapirotto** [comment]
I suspected I was doing something wrong! Thanks a lot!
