### ISSUE TITLE
[feature request] Test triggers via cmdline and UI

### ISSUE THREAD

**Issue by davidevertuani** [getwud/wud#500]
Related to: #459 

Would be nice and helpful to be able to issue a test notification on a given trigger.
Requesting:

- command line command and,
-  a "Test" button under <ip>/configuration/triggers

to emit a test notification on request to evaluate the correctness of triggers config.

**Comment by fmartinou** [comment]
Great idea 👍

**Comment by fmartinou** [comment]
What it looks like

![image](https://github.com/user-attachments/assets/a083d17f-b17e-4472-b0a5-28f03a915057)

**Comment by davidevertuani** [comment]
That was fast! Thanks for the implementation.
Used it to debug my Apprise configuration, working nicely.
Maybe consider adding the ability to edit the trigger tag, url/urls and config name for increased flexibility during debugging :)
