### ISSUE TITLE
 Problem with postgres 16.3 being offered 17.2-bullseye

### ISSUE THREAD

**Issue by irdet2** [getwud/wud#509]
Hello! 

I am a new user to WUD and so far I absolutely love it! 

I am trying to set the update for a few of my running containers but I have a problem with Postgres.

I have `16.3` installed and WUD is offering the update to be `17.2-bullseye`.

I understand that by using tags I can go and select the digits and the versions. So I have included the following:

```
- wud.tag.include=^\d+\.\d+
- wud.tag.transform=^(\d+\.\d+) => $$1
```

I don't mind going from `16 -> 17` to start with `^16`  what concerns me is that `-bullseye` part shouldn't be here. Am I thinking something wrong about it?

To be honest I was expecting the plain `wud.tag.include=^\d+\.\d+` to work without the transformation but nevertheless both of them are bringing as candidates the `17.2-bullseye`

Here is a screenshot

![Screenshot 2024-12-12 at 23 59 42](https://github.com/user-attachments/assets/b28b29c4-d11d-4a60-b920-64aebe9b8d2a)

**Comment by irdet2** [comment]
I found a solution for the above. 

I had to change 
`- wud.tag.include=^\d+\.\d+`

to 
`- wud.tag.include=^\d+\.\d+$`

although it shouldn't....Any explanations?

**Comment by fmartinou** [comment]
Hi,

This is working:

```yaml
services:

  postgres:
    image: postgres:16.3
    labels:
      - wud.tag.include=^\d+\.\d+$$
```

(don't forget that on docker-compose `$` must be doubled to avoid docker-compose to interpolate them.)

![image](https://github.com/user-attachments/assets/d2fdcd56-056e-4647-83a0-38df273da4bd)
