### ISSUE TITLE
Feature branches not tagged as latest

### ISSUE THREAD

**Issue by dkadioglu** [getwud/wud#513]
Hi,

I just stumbled upon the fact, that pull requests in the wud repository are automatically built as Docker images and uploaded to Docker Hub, which is fine. However, from my point of view it doesn't make sense to tag those builds also as latest. Currently the latest build is 5 hours old as is the build of feature__502_specific_triggers, which has not been merged so far. Could that be changed or could you explain, if you do that on purpose? Thanks.

**Comment by fmartinou** [comment]
Hi,

That's strange (and not expected) 🤔 .

Only the images built from the `main` branch should be tagged as `latest`:
https://github.com/getwud/wud/blob/main/.travis.yml#L194

**Comment by fmartinou** [comment]
I reworked the travis ci; `latest` tags should now only be pushed when building a new tag (https://github.com/getwud/wud/commit/38f0ed6239255f2104c2cb59c62d224492123eed#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485) 🤞
