### ISSUE TITLE
Shorter digest in triggers

### ISSUE THREAD

**Issue by orenhecht** [getwud/wud#520]
While I understand the push towards using semver, I have some containers that I want to keep using the latest tag and get notification when their digest changes. 
However, getting the notification with the full digest both in the local and remote creates a very long message:
`Container homepage running with digest sha256:9a82d5773ccfcb73ba341619fd44790a30750731568c25a6e070c2c44aa30bde can be updated to digest sha256:6cdd479147e4d2f1f853c7205ead7e2a0b0ccbad6e3ff0986e01936cbd179c17`

How about adding a configuration `WUD_TRIGGER_TELEGRAM_1_SIMPLEBODY_SHORT_DIGEST=true` that will shorten digests if the update kind is digest?

Another option can be to add `${local-short}` and `${remote-short}` which will only shorten digests, but I think it is less intuitive.

I can submit a PR for this change, but before I do I want to know if you agree to add this functionality in the manner suggested, or do you have another better way to do it?

**Comment by fmartinou** [comment]
Hi,

Your request makes sense 👍 

I take this opportunity to improve the current template system to allow to execute any valid js expression.

So for shorter digests, you could then write a template like:
```
WUD_TRIGGER_{trigger_type}_{trigger_name}_SIMPLEBODY=Container ${name} can be updated from ${local.substring(0, 15)} to ${remote.substring(0, 15)}
```

(It will give you `Container homepage can be updated from sha256:9a82d577 to sha256:6cdd4791`)

**Comment by orenhecht** [comment]
thanks @fmartinou ! much appreciated!
