### ISSUE TITLE
Question: do i have to set labels for each container when using WUD_WATCHER_CGM1_WATCHBYDEFAULT=true

### ISSUE THREAD

**Issue by carmatana** [getwud/wud#529]
I want to have all containers monitored and updated (dockercompose)

I have a lot of containers and I do not want to set labels for each of them, only for the ones that I want to exclude

I understand that WUD_WATCHER_CGM1_WATCHBYDEFAULT=true will do that

Is this rigth ?

**Comment by fmartinou** [comment]
Hi,

Yes, it's right.

You can chose the best strategy based on your situation:
- Either watching by default **ALL** containers but excluding some of them by setting `wud.watch=false` on them
- Or watching by default **NO** containers but including some of them by setting `wud.watch=true` on them
