### ISSUE TITLE
[bug] Pick specific trigger for specific container: It does not work

### ISSUE THREAD

**Issue by carmatana** [getwud/wud#531]
This feature seems to be not working

I have the following trriger:

        - WUD_TRIGGER_PUSHOVER_CGM1_MODE=batch

and then in my service:

services:

  syncthing:
       image: syncthing/syncthing:1.27.1
       labels:
            - wud.trigger.exclude=pushover.cgm1
       
 But the trigger is still associated after a complete remove and recreation of wud

<img width="961" alt="image" src="https://github.com/user-attachments/assets/75cc526d-9836-4bc2-81b9-4e4c589b7978" />

The complete trigger json:

[{"id":"pushover.cgm1","type":"pushover","name":"cgm1","configuration":{"token":"a****************************h","device":"OnePlus10","user":"u****************************z","mode":"batch","once":false,"batchtitle":"${count} updates available","simplebody":"${name} can be updated from version ${local} to version ${remote}","html":0,"sound":"pushover","priority":0,"threshold":"all","simpletitle":"New ${kind} found for container ${name}"}}]

_Originally posted by @carmatana in https://github.com/getwud/wud/issues/502#issuecomment-2563263046_

**Comment by fmartinou** [comment]
Hi,

You're right 👍 
A global change about entity ids broke this feature 😞 .
I found the issue; the fix will be released very soon along with other features currently in progress.
