### ISSUE TITLE
Enhancement - Improve Error Handling & Logging

### ISSUE THREAD

**Issue by samcro1967** [getwud/wud#536]
With the latest update, WUD no longer adds any containers after starting with a fresh store folder.  The only error message I get with debug logging enabled is the following:
```
08:14:23.247  WARN whats-up-docker/watcher.docker.local: Error when trying to get the list of the containers to watch (Cannot read properties of undefined (reading 'indexOf'))
```

Is there any way to get more logging to determine what registry or container is causing the issue?

Also would be good if WUD was able to handle errors like this and skip the offending registry or container and still show everything else rather than show nothing.

**Comment by fmartinou** [comment]
Hi,

If you're using the latest version, you may be impacted by breaking changes planned for the upcoming unreleased `8.0.0`:
https://getwud.github.io/wud/#/changelog/?id=_800-wip

Do you have custom registry configuration? If so you have to rename your env vars to comply with the new convention.

For example,
`WUD_REGISTRY_LSCR_USERNAME` becomes `WUD_REGISTRY_LSCR_PRIVATE_USERNAME` and so on
(the purpose of this change is to allow to configure multiple registries of the same type)

**Comment by samcro1967** [comment]
I saw the release notes and had already updated hub and lscr.  Did not catch that custom also changed.  Updating to the new environment label for custom registries has it working again.
 
Would still be good if there was better logging when errors are encountered to point folks to the issue as well as continue on with other registries.  I would also suggest adding a note in the logs when deprecated labels are detected.  Might help cut down in issues for you.

Appreciate your hard work on this project and quick response.
