### ISSUE TITLE
[request] add "TTL" support to Pushover trigger

### ISSUE THREAD

**Issue by carmatana** [getwud/wud#538]
In addition to priority and other parameters, Pushover allows to set TTL (time to live) in their API

this is the time, in seconds, that the notification (and the message) lives

after that time the notifications is deleted.

Very nice to not have a lot of messages to handle

**Comment by fmartinou** [comment]
I just added the option (`WUD_TRIGGER_PUSHOVER_{trigger_name}_TTL`).
(I haven't tested but I see no reason why it won't work 🤞 )

**Comment by carmatana** [comment]
Thanks !

Once released I will report back if there's an issue
